version: '3.8'

services:
  mongo_db:
    container_name: mongo_db
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: chat
    ports:
      - '27017:27017'
    networks:
      - my_network

  nest_app:
    container_name: nest_app
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongo_db
    environment:
      - MONGO_URI=mongodb://root:root@mongo_db:27017/chat
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
